[tool.poetry]
name = "pgutils"
version = "0.0.1"
description = "A library to help managing multiple database connections using SQLAlchemy with PostgreSQL"
authors = ["Bruno Peixoto <brunolnetto@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.10"
pydantic = "^2.9.2"

[tool.poetry.dev-dependencies]

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.3"
pytest-cov = "^5.0.0"
sqlalchemy = "^2.0.35"
asyncpg = "^0.29.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
