name: Test Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Host Databases, Run Tests, and Upload Coverage Reports

    steps:
    - uses: actions/checkout@v4

    - name: Setup PostgreSQL
      uses: tj-actions/install-postgresql@v3
      with:
        postgresql-version: 16

    #----------------------------------------------
    #       Install Python
    #----------------------------------------------
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    #----------------------------------------------
    #       install & configure uv
    #----------------------------------------------
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "0.5.1"

    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --all-extras --dev

    # Run tests and generate coverage report
    - name: Run Tests with Coverage
      run: |
        uv run pytest --cov=pgbase tests/
        mkdir -p coverage-reports
        mv .coverage coverage-reports/coverage.xml

    # Upload Coverage Report to Codecov
    - name: Upload Coverage Reports to Codecov
      run: |
        curl -Os https://uploader.codecov.io/latest/linux/codecov
        chmod +x codecov
        ./codecov -t ${{ secrets.CODECOV_TOKEN }} -f coverage-reports/coverage.xml
