name: CI Workflow

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    name: Host Databases, Run Tests, and Upload Coverage Reports

    steps:
    - uses: actions/checkout@v4

    # Set up Docker and Docker Compose
    - name: Install Docker
      run: |
        sudo apt-get update
        sudo apt-get install -y apt-transport-https ca-certificates curl software-properties-common
        curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
        sudo add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
        sudo apt-get update
        sudo apt-get install -y docker-ce

    - name: Install Docker Compose
      run: |
        DOCKER_COMPOSE_VERSION=1.29.2  # Specify the desired version
        sudo curl -L "https://github.com/docker/compose/releases/download/$DOCKER_COMPOSE_VERSION/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
        sudo chmod +x /usr/local/bin/docker-compose

    - name: Verify Docker Installation
      run: |
        docker --version
        docker-compose --version

    # Start PostgreSQL container
    - name: Build and Start Docker Containers
      run: docker-compose -f ./docker-compose.yaml up -d

    # Wait for the PostgreSQL database to be ready
    - name: Wait for Database to be Ready
      run: |
        until docker exec postgres-db pg_isready -U postgres; do
          sleep 1
        done

    # Run database initialization commands
    - name: Initialize Database
      run: |
        docker exec -i postgres-db psql -U postgres <<EOF
        CREATE DATABASE "postgres-local";
        GRANT ALL PRIVILEGES ON DATABASE "postgres-local" TO postgres;
        ALTER USER postgres WITH PASSWORD 'postgres';
        EOF

    # Additional CI steps go here (e.g., tests, coverage)
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'

    - name: Install and configure Poetry
      uses: snok/install-poetry@v1
      with:
        virtualenvs-create: true
        virtualenvs-in-project: true

    # Install dependencies and run tests
    - name: Install dependencies and Run Tests
      run: |
        poetry install --verbose --no-interaction
        poetry run pytest --cov=pgbase tests/

    # Stop and clean up the database container
    - name: Stop Docker Containers
      run: docker-compose -f docker-compose.yaml down
